#!/bin/bash
set -e

# Sheldon Installer
# Usage: curl -fsSL https://raw.githubusercontent.com/bowerhall/sheldon/main/core/scripts/install.sh | sudo bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

REPO_URL="https://raw.githubusercontent.com/bowerhall/sheldon/main"
INSTALL_DIR="/opt/sheldon"

echo ""
echo -e "${GREEN}"
cat << "EOF"
   _____ __         __    __
  / ___// /_  ___  / /___/ /___  ____
  \__ \/ __ \/ _ \/ / __  / __ \/ __ \
 ___/ / / / /  __/ / /_/ / /_/ / / / /
/____/_/ /_/\___/_/\__,_/\____/_/ /_/

         I N S T A L L E R
EOF
echo -e "${NC}"

# Check root
if [[ $EUID -ne 0 ]]; then
    echo -e "${RED}Run as root: sudo bash${NC}"
    exit 1
fi

echo -e "${GREEN}[1/5]${NC} Installing Docker..."
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com | sh
else
    echo "Docker already installed"
fi

echo ""
echo -e "${GREEN}[2/5]${NC} Downloading Sheldon..."
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# Download compose file from repo (single source of truth)
curl -fsSL "$REPO_URL/core/deploy/docker-compose.simple.yml" -o docker-compose.yml
echo "Downloaded docker-compose.yml"

echo ""
echo -e "${GREEN}[3/5]${NC} Configuration"
echo ""
echo "======================================"
echo ""

read -p "Telegram bot token (from @BotFather): " telegram_token < /dev/tty
while [[ -z "$telegram_token" ]]; do
    echo -e "${RED}Telegram token is required${NC}"
    read -p "Telegram bot token: " telegram_token < /dev/tty
done

read -p "Your Telegram chat ID (from @userinfobot): " owner_chat_id < /dev/tty

echo ""
echo "Enter at least one LLM API key:"
read -p "KIMI_API_KEY (recommended, Enter to skip): " kimi_key < /dev/tty
read -p "ANTHROPIC_API_KEY (Enter to skip): " anthropic_key < /dev/tty
read -p "OPENAI_API_KEY (Enter to skip): " openai_key < /dev/tty

# Validate at least one key
if [[ -z "$kimi_key" && -z "$anthropic_key" && -z "$openai_key" ]]; then
    echo -e "${RED}At least one API key is required${NC}"
    exit 1
fi

echo ""
echo "Your timezone (for reminders/crons), e.g., Europe/London, America/New_York"
read -p "Timezone: " timezone < /dev/tty
while [[ -z "$timezone" ]]; do
    echo -e "${RED}Timezone is required${NC}"
    read -p "Timezone: " timezone < /dev/tty
done

# Generate passwords
storage_admin_password=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)
storage_sheldon_password=$(openssl rand -base64 16 | tr -dc 'a-zA-Z0-9' | head -c 16)

echo ""
echo -e "MinIO admin password (auto-generated): ${YELLOW}${storage_admin_password}${NC}"
echo "Save this for MinIO console access."

# Write .env file
cat > "$INSTALL_DIR/.env" << EOF
# Sheldon Configuration
# Generated by installer on $(date)

# Telegram
TELEGRAM_TOKEN=${telegram_token}
OWNER_CHAT_ID=${owner_chat_id}

# LLM API Keys (at least one required)
KIMI_API_KEY=${kimi_key}
ANTHROPIC_API_KEY=${anthropic_key}
OPENAI_API_KEY=${openai_key}

# Timezone
TZ=${timezone}

# Storage (MinIO)
STORAGE_ADMIN_PASSWORD=${storage_admin_password}
STORAGE_SHELDON_PASSWORD=${storage_sheldon_password}

# Host paths (for Docker volume mounts)
HOST_DATA_DIR=/opt/sheldon/data
EOF

chmod 600 "$INSTALL_DIR/.env"

echo ""
echo -e "${GREEN}[4/5]${NC} Pulling images..."

# Pull all required images
docker pull ghcr.io/bowerhall/sheldon:latest
docker pull ghcr.io/bowerhall/sheldon-coder-sandbox:latest
docker pull ghcr.io/bowerhall/sheldon-browser-sandbox:latest
docker pull ollama/ollama
docker pull minio/minio:latest
docker pull minio/mc:latest
docker pull tecnativa/docker-socket-proxy

echo ""
echo -e "${GREEN}[5/5]${NC} Starting Sheldon..."

# Create data directory
mkdir -p "$INSTALL_DIR/data"
chown -R 1000:1000 "$INSTALL_DIR/data"

# Start services
cd "$INSTALL_DIR"
docker compose up -d

echo ""
echo "Waiting for services to start..."
for i in {1..30}; do
    if docker ps --filter "name=sheldon" --filter "status=running" | grep -q sheldon; then
        echo -e "${GREEN}Sheldon is running!${NC}"
        break
    fi
    if [ $i -eq 30 ]; then
        echo -e "${RED}Sheldon failed to start. Check logs:${NC}"
        docker logs sheldon --tail 20
        exit 1
    fi
    sleep 2
done

# Create systemd service for auto-start
cat > /etc/systemd/system/sheldon.service << 'SERVICE'
[Unit]
Description=Sheldon AI Assistant
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/sheldon
ExecStart=/usr/bin/docker compose up -d
ExecStop=/usr/bin/docker compose down
TimeoutStartSec=300

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable sheldon

PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "your-server-ip")

echo ""
echo "======================================"
echo -e "   ${GREEN}Sheldon is running!${NC}"
echo "======================================"
echo ""
echo "Open Telegram and message your bot."
echo ""
echo "MinIO console (localhost only):"
echo "  ssh -L 9001:localhost:9001 root@${PUBLIC_IP}"
echo "  then open http://localhost:9001"
echo "  Username: admin"
echo "  Password: ${storage_admin_password}"
echo ""
echo "Commands:"
echo "  docker logs -f sheldon    - View logs"
echo "  docker compose restart    - Restart"
echo "  docker compose down       - Stop"
echo ""
echo "Config: $INSTALL_DIR/.env"
echo "Data:   $INSTALL_DIR/data"
echo ""
